language: python

matrix:
  include:
    - os: linux
    - os: osx
      # workaround for https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      # end of workaround

python: 3.6

install:
  - python -c "import sys; assert sys.version_info[:2] == (3,6)"
  - make

script:
  - make test
